/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bancopoo;

import dados.BdBanco;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

import objetos.Email;
import objetos.Usuario;

/**
 *
 * @author Fael
 */
public class painelTransacoes extends javax.swing.JFrame {
    
    BdBanco db = new BdBanco();
    JButton botaoTransacoes;
    Usuario usuario_logado;
    
    Email email2 = new Email();
    
    /**
     * Creates new form painelTransacoes
     */
    public painelTransacoes(Usuario usuario_logado, JButton botaoTransacoes) {
        ImageIcon icon = new ImageIcon("src/img/bank.png"); // Substitua pelo caminho do ícone .ico ou .png
        setIconImage(icon.getImage());
        initComponents();
        
        this.usuario_logado = usuario_logado;
        this.botaoTransacoes = botaoTransacoes;
        db.conectar();
        if(db.estaConectado()){
            db.atualizarTabelaTransacoes(usuario_logado.getCpf(), tabelaTransacoes);
        }
        db.desconectar();
        email2.criaExcelAPartirDaTabela(tabelaTransacoes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTransacoes = new javax.swing.JPanel();
        PanelTabelaTran = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTransacoes = new javax.swing.JTable();
        PanelHeaderTransacoes = new javax.swing.JPanel();
        LabelTransacoes = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        botaoEmail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelTransacoes.setBackground(new java.awt.Color(248, 237, 248));
        PanelTransacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PanelTabelaTran.setBackground(new java.awt.Color(248, 237, 248));

        tabelaTransacoes.setAutoCreateRowSorter(true);
        tabelaTransacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaTransacoes.setForeground(new java.awt.Color(38, 15, 38));
        tabelaTransacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICAÇÃO", "CPF", "DESCRIÇÃO", "VALOR", "SALDO", "DATA"
            }
        ));
        jScrollPane1.setViewportView(tabelaTransacoes);

        javax.swing.GroupLayout PanelTabelaTranLayout = new javax.swing.GroupLayout(PanelTabelaTran);
        PanelTabelaTran.setLayout(PanelTabelaTranLayout);
        PanelTabelaTranLayout.setHorizontalGroup(
            PanelTabelaTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelaTranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTabelaTranLayout.setVerticalGroup(
            PanelTabelaTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTabelaTranLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        PanelHeaderTransacoes.setBackground(new java.awt.Color(38, 15, 38));

        LabelTransacoes.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelTransacoes.setForeground(new java.awt.Color(255, 255, 255));
        LabelTransacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTransacoes.setText("Transações");

        javax.swing.GroupLayout PanelHeaderTransacoesLayout = new javax.swing.GroupLayout(PanelHeaderTransacoes);
        PanelHeaderTransacoes.setLayout(PanelHeaderTransacoesLayout);
        PanelHeaderTransacoesLayout.setHorizontalGroup(
            PanelHeaderTransacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderTransacoesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(LabelTransacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHeaderTransacoesLayout.setVerticalGroup(
            PanelHeaderTransacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderTransacoesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LabelTransacoes)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        botaoSair.setBackground(new java.awt.Color(227, 38, 54));
        botaoSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("SAIR");
        botaoSair.setToolTipText("Sair");
        botaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoEmail.setBackground(new java.awt.Color(51, 153, 255));
        botaoEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoEmail.setForeground(new java.awt.Color(255, 255, 255));
        botaoEmail.setText("EXPORTAR EXTRATO");
        botaoEmail.setToolTipText("Exportar histórico de transações");
        botaoEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTransacoesLayout = new javax.swing.GroupLayout(PanelTransacoes);
        PanelTransacoes.setLayout(PanelTransacoesLayout);
        PanelTransacoesLayout.setHorizontalGroup(
            PanelTransacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTransacoesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(PanelTabelaTran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addComponent(PanelHeaderTransacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTransacoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        PanelTransacoesLayout.setVerticalGroup(
            PanelTransacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTransacoesLayout.createSequentialGroup()
                .addComponent(PanelHeaderTransacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTabelaTran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTransacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(botaoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTransacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTransacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        botaoTransacoes.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEmailActionPerformed
        String destinatario = usuario_logado.getEmail();
        String assunto = "Extrato bancário 3F";
        String texto = "Prezado(a) "+usuario_logado.getNome()+",\n" +
                        "\n" +
                        "Segue em anexo o seu extrato bancário. Este extrato contém informações detalhadas sobre as transações realizadas em sua conta bancária durante todo período.\n" +
                        "\n" +
                        "Por favor, reveja o extrato para garantir que todas as transações estejam corretas e em conformidade com suas atividades financeiras.\n" +
                        "\n" +
                        "Se você tiver alguma dúvida ou precisar de esclarecimentos adicionais sobre alguma transação específica, não hesite em entrar em contato conosco.\n" +
                        "\n" +
                        "Atenciosamente, 3F";
                
        if(email2.enviaEmailComAnexo(destinatario, assunto, texto)){
            JOptionPane.showMessageDialog(null, "O extrato foi enviado para o seu email com sucesso!",
                                          "Envio de Extrato Bancário", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Houve um erro ao enviar o extrato por email. Verifique seu email",
                                          "Erro no Envio de Extrato", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_botaoEmailActionPerformed

    
    //yishuykvunrmmzyv
    
    
       
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTransacoes;
    private javax.swing.JPanel PanelHeaderTransacoes;
    private javax.swing.JPanel PanelTabelaTran;
    private javax.swing.JPanel PanelTransacoes;
    private javax.swing.JButton botaoEmail;
    private javax.swing.JButton botaoSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTransacoes;
    // End of variables declaration//GEN-END:variables
}
