
package bancopoo;

import dados.BdBanco;
import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import objetos.Email;
import objetos.Usuario;



public class painelSacar extends javax.swing.JFrame {
    BdBanco db = new BdBanco();
    Usuario usuario_logado;
    JButton botaoSacar2;
    Email email2 = new Email();
   
    public painelSacar(Usuario usuario_logado, JButton botaoSacar) {
        ImageIcon icon = new ImageIcon("src/img/bank.png"); // Substitua pelo caminho do ícone .ico ou .png
        setIconImage(icon.getImage());
        
        initComponents();
        this.usuario_logado = usuario_logado;
        this.botaoSacar2 = botaoSacar;

        DecimalFormat formato = new DecimalFormat("0.00");
        labelSaldo.setText("R$ " + String.valueOf(formato.format(usuario_logado.getSaldo())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSaldo = new javax.swing.JLabel();
        SeuSaldo = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        campoQuantidade = new javax.swing.JTextField();
        botaoSacar = new javax.swing.JButton();
        labelErro = new javax.swing.JLabel();
        botaoCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanelHeaderSaque = new javax.swing.JPanel();
        labelSaque = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Área de saque");
        setBackground(new java.awt.Color(10, 124, 204));
        setMaximumSize(new java.awt.Dimension(280, 170));
        setMinimumSize(new java.awt.Dimension(280, 170));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(280, 146));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(280, 230));
        jPanel1.setMinimumSize(new java.awt.Dimension(280, 230));

        labelSaldo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        labelSaldo.setForeground(new java.awt.Color(38, 15, 38));
        labelSaldo.setText(" ");
        labelSaldo.setToolTipText("Seu saldo");
        labelSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SeuSaldo.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        SeuSaldo.setForeground(new java.awt.Color(38, 15, 38));
        SeuSaldo.setText("Seu saldo:");

        labelQuantidade.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        labelQuantidade.setForeground(new java.awt.Color(38, 15, 38));
        labelQuantidade.setLabelFor(campoQuantidade);
        labelQuantidade.setText("Digite a quantidade:");

        campoQuantidade.setBackground(new java.awt.Color(248, 237, 248));
        campoQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        campoQuantidade.setForeground(new java.awt.Color(38, 15, 38));
        campoQuantidade.setToolTipText("Quantidade a ser sacada");
        campoQuantidade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));
        campoQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQuantidadeActionPerformed(evt);
            }
        });

        botaoSacar.setBackground(new java.awt.Color(81, 223, 132));
        botaoSacar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSacar.setForeground(new java.awt.Color(38, 15, 38));
        botaoSacar.setText("SACAR");
        botaoSacar.setToolTipText("Realizar saque");
        botaoSacar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSacarActionPerformed(evt);
            }
        });

        labelErro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelErro.setForeground(new java.awt.Color(255, 51, 51));
        labelErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelErro.setText(" ");

        botaoCancelar.setBackground(new java.awt.Color(227, 38, 54));
        botaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCancelar.setText("CANCELAR");
        botaoCancelar.setToolTipText("Cancelar saque");
        botaoCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(38, 15, 38));
        jLabel1.setLabelFor(campoDescricao);
        jLabel1.setText("Descrição:");

        PanelHeaderSaque.setBackground(new java.awt.Color(153, 0, 51));

        labelSaque.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelSaque.setForeground(new java.awt.Color(255, 255, 255));
        labelSaque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaque.setText("Saque");

        javax.swing.GroupLayout PanelHeaderSaqueLayout = new javax.swing.GroupLayout(PanelHeaderSaque);
        PanelHeaderSaque.setLayout(PanelHeaderSaqueLayout);
        PanelHeaderSaqueLayout.setHorizontalGroup(
            PanelHeaderSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderSaqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHeaderSaqueLayout.setVerticalGroup(
            PanelHeaderSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderSaqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSaque, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        campoDescricao.setBackground(new java.awt.Color(248, 237, 248));
        campoDescricao.setColumns(17);
        campoDescricao.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        campoDescricao.setForeground(new java.awt.Color(38, 15, 38));
        campoDescricao.setRows(5);
        jScrollPane1.setViewportView(campoDescricao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHeaderSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SeuSaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 13, Short.MAX_VALUE)
                                .addComponent(botaoSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(PanelHeaderSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SeuSaldo)
                            .addComponent(labelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelQuantidade)
                            .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelErro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSacarActionPerformed
        if(campoQuantidade.getText().isEmpty() || campoQuantidade.getText().equals("")){
            labelErro.setForeground(new java.awt.Color(255, 51, 51));
            labelErro.setText("Campos vazios");
        }else{
            campoQuantidade.setText(campoQuantidade.getText().replace(",", "."));
            Double quantidadeSacar = Double.parseDouble(campoQuantidade.getText());
            db.conectar();
            if(db.estaConectado()){
                Double saldoAtual = usuario_logado.getSaldo();
                if(saldoAtual<quantidadeSacar){
                    Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img/sem-saldo.png")); 
                    JOptionPane.showMessageDialog(rootPane, "Seu Saldo é insuficiente para esta ação", "SALDO INSUFICIENTE", JOptionPane.INFORMATION_MESSAGE, icon);
                }else{
                    try{
                        String descricao = campoDescricao.getText();
                        Double saldoNovo = saldoAtual - quantidadeSacar;

                        db.setSaldo(usuario_logado.getCpf(), saldoNovo);

                        usuario_logado.setSaldo(saldoNovo);
                        labelSaldo.setText(String.valueOf( usuario_logado.getSaldo()));


                        db.inserirTransacao(usuario_logado.getCpf(), "Saque -- " +descricao , quantidadeSacar, saldoNovo);

                        String destinatario = usuario_logado.getEmail();
                        String assunto = "Saque 3F";
                        String texto = "Olá " + usuario_logado.getNome() + ",\n\n"
                                + "O saque de sua conta foi realizado com sucesso.\n"
                                + "Valor do Saque: R$" + quantidadeSacar + "\n"
                                + "Saldo Atual: R$" + saldoNovo + "\n"
                                + "Descrição: " + descricao + "\n\n"
                                + "Agradecemos por escolher nossos serviços bancários.\n\n"
                                + "Atenciosamente,\n"
                                + "Equipe do Banco 3F";

                        email2.enviaEmailSemAnexo(destinatario, assunto, texto);
                        this.dispose();
                        botaoSacar2.setEnabled(true);
                    }catch(Exception e){
                        labelErro.setText("Erro");
                    }
                }
            }
            db.desconectar();
        }
    }//GEN-LAST:event_botaoSacarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
        botaoSacar2.setEnabled(true);
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void campoQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQuantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHeaderSaque;
    private javax.swing.JLabel SeuSaldo;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSacar;
    private javax.swing.JTextArea campoDescricao;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelErro;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelSaque;
    // End of variables declaration//GEN-END:variables
}
