/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bancopoo;
import dados.BdBanco;
import javax.swing.ImageIcon;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import objetos.Usuario;
/**
 *
 * @author henri
 */
public class painelEditarUsuario extends javax.swing.JFrame {
    BdBanco db = new BdBanco();
    
    Usuario usuario_logado;
    JButton botaoEditar;
    
    
    /**
     * Creates new form painelEditarUsuario
     */
    public painelEditarUsuario(Usuario usuario_logado, JButton botaoEditar) {
        ImageIcon icon = new ImageIcon("src/img/bank.png"); // Substitua pelo caminho do ícone .ico ou .png
        setIconImage(icon.getImage());
        
        
        initComponents();
        
        this.usuario_logado = usuario_logado;
        
        this.botaoEditar = botaoEditar;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEdit = new javax.swing.JPanel();
        labelErro = new javax.swing.JLabel();
        botaoSalvarEdicao = new javax.swing.JButton();
        botaoCancelarCadastro = new javax.swing.JButton();
        comboDadoASerEditado = new javax.swing.JComboBox<>();
        LabelOqueEdit = new javax.swing.JLabel();
        campoNovoDado = new javax.swing.JTextField();
        labelNovoDado = new javax.swing.JLabel();
        PanelEditHeader = new javax.swing.JPanel();
        LabelEdit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Área de editar os dados");
        setBackground(new java.awt.Color(10, 124, 204));
        setUndecorated(true);
        setResizable(false);

        PanelEdit.setBackground(new java.awt.Color(255, 255, 255));
        PanelEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelErro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelErro.setForeground(new java.awt.Color(255, 51, 51));
        labelErro.setText(" ");

        botaoSalvarEdicao.setBackground(new java.awt.Color(81, 223, 132));
        botaoSalvarEdicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSalvarEdicao.setForeground(new java.awt.Color(255, 255, 255));
        botaoSalvarEdicao.setText("SALVAR");
        botaoSalvarEdicao.setToolTipText("Salvar mudança");
        botaoSalvarEdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSalvarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarEdicaoActionPerformed(evt);
            }
        });

        botaoCancelarCadastro.setBackground(new java.awt.Color(227, 38, 54));
        botaoCancelarCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCancelarCadastro.setForeground(new java.awt.Color(255, 255, 255));
        botaoCancelarCadastro.setText("CANCELAR");
        botaoCancelarCadastro.setToolTipText("Cancelar mudança");
        botaoCancelarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarCadastroActionPerformed(evt);
            }
        });

        comboDadoASerEditado.setBackground(new java.awt.Color(248, 237, 248));
        comboDadoASerEditado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        comboDadoASerEditado.setForeground(new java.awt.Color(38, 15, 38));
        comboDadoASerEditado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "nome", "sobrenome", "email", "senha", "sexo", "celular", "rua", "bairro", "numero", "cidade", "estado", "cep", "foto" }));
        comboDadoASerEditado.setToolTipText("Dado a ser editado");
        comboDadoASerEditado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDadoASerEditadoItemStateChanged(evt);
            }
        });
        comboDadoASerEditado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDadoASerEditadoActionPerformed(evt);
            }
        });

        LabelOqueEdit.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        LabelOqueEdit.setForeground(new java.awt.Color(38, 15, 38));
        LabelOqueEdit.setText("A ser editado: ");

        campoNovoDado.setBackground(new java.awt.Color(248, 237, 248));
        campoNovoDado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoNovoDado.setForeground(new java.awt.Color(38, 15, 38));
        campoNovoDado.setText(" ");
        campoNovoDado.setToolTipText("Alteração a ser realizada");

        labelNovoDado.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        labelNovoDado.setForeground(new java.awt.Color(38, 15, 38));
        labelNovoDado.setText("Novo dado:");

        PanelEditHeader.setBackground(new java.awt.Color(38, 15, 38));

        LabelEdit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelEdit.setForeground(new java.awt.Color(255, 255, 255));
        LabelEdit.setText("Editar Perfil");

        javax.swing.GroupLayout PanelEditHeaderLayout = new javax.swing.GroupLayout(PanelEditHeader);
        PanelEditHeader.setLayout(PanelEditHeaderLayout);
        PanelEditHeaderLayout.setHorizontalGroup(
            PanelEditHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LabelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEditHeaderLayout.setVerticalGroup(
            PanelEditHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelEditLayout = new javax.swing.GroupLayout(PanelEdit);
        PanelEdit.setLayout(PanelEditLayout);
        PanelEditLayout.setHorizontalGroup(
            PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEditHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelEditLayout.createSequentialGroup()
                .addGroup(PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelEditLayout.createSequentialGroup()
                        .addGroup(PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEditLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(labelNovoDado)
                                .addGap(18, 18, 18)
                                .addGroup(PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelEditLayout.createSequentialGroup()
                                        .addComponent(botaoSalvarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botaoCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoNovoDado)))
                            .addGroup(PanelEditLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(LabelOqueEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboDadoASerEditado, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelEditLayout.setVerticalGroup(
            PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditLayout.createSequentialGroup()
                .addComponent(PanelEditHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelOqueEdit)
                    .addComponent(comboDadoASerEditado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNovoDado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNovoDado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErro, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarCadastroActionPerformed
        this.dispose();
        botaoEditar.setEnabled(true);

    }//GEN-LAST:event_botaoCancelarCadastroActionPerformed

    private void botaoSalvarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarEdicaoActionPerformed
        db.conectar();
        if(db.estaConectado()){
            String dadoASerEditado = String.valueOf(comboDadoASerEditado.getSelectedItem());
            if(dadoASerEditado != null || !dadoASerEditado.isEmpty()) {
                String novoDado = campoNovoDado.getText();
                if(novoDado != null || !novoDado.isEmpty()) {
                    
                    db.editarUsuarioDB(usuario_logado.getCpf(), dadoASerEditado, novoDado);
                    this.usuario_logado = db.carregaDadosDB(usuario_logado.getCpf());
                    JOptionPane.showMessageDialog(null, "Os dados foram salvos com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    comboDadoASerEditado.setSelectedItem("");
                    campoNovoDado.setText("");
                    this.dispose();
                    botaoEditar.setEnabled(true);
                }else{
                    labelErro.setText("Novo dado não pode ser vazio!");
                }
            }else{
                labelErro.setText("O dado a ser editado não pode ser vazio!");
            }
        }
        db.desconectar();
    }//GEN-LAST:event_botaoSalvarEdicaoActionPerformed

    private void comboDadoASerEditadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDadoASerEditadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDadoASerEditadoActionPerformed

    private void comboDadoASerEditadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDadoASerEditadoItemStateChanged
        db.conectar();
        if(db.estaConectado()){
            if(!String.valueOf(comboDadoASerEditado.getSelectedItem()).isEmpty()){
                String dadoASerEditado = String.valueOf(comboDadoASerEditado.getSelectedItem());
                campoNovoDado.setText(db.getDado(usuario_logado.getCpf(), dadoASerEditado));
            }
            
        }
        db.desconectar();
    }//GEN-LAST:event_comboDadoASerEditadoItemStateChanged
                 
    
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEdit;
    private javax.swing.JLabel LabelOqueEdit;
    private javax.swing.JPanel PanelEdit;
    private javax.swing.JPanel PanelEditHeader;
    private javax.swing.JButton botaoCancelarCadastro;
    private javax.swing.JButton botaoSalvarEdicao;
    private javax.swing.JTextField campoNovoDado;
    private javax.swing.JComboBox<String> comboDadoASerEditado;
    private javax.swing.JLabel labelErro;
    private javax.swing.JLabel labelNovoDado;
    // End of variables declaration//GEN-END:variables
}
