/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bancopoo;

import dados.BdBanco;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import objetos.Email;
import objetos.Usuario;

/**
 *
 * @author henri
 */
public class painelDepositar extends javax.swing.JFrame {
    private Usuario usuario_logado;
    BdBanco db = new BdBanco();
    JButton botaoDepositar;
    Email email2 = new Email();
    
    /**
     * Creates new form painelDepositar
     */
    public painelDepositar(Usuario usuario_logado, JButton botaoDepositar) {
        ImageIcon icon = new ImageIcon("src/img/bank.png"); // Substitua pelo caminho do ícone .ico ou .png
        setIconImage(icon.getImage());
        initComponents();
        
        
        
        this.usuario_logado = usuario_logado;
        this.botaoDepositar = botaoDepositar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelIcone = new javax.swing.JLabel();
        labelOlaUsuario = new javax.swing.JLabel();
        labelNomeUsuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelConta = new javax.swing.JLabel();
        labelAgencia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        PanelDep = new javax.swing.JPanel();
        labelQuantidade = new javax.swing.JLabel();
        campoQuantidade = new javax.swing.JTextField();
        botaoGerarBoleto = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        LabelDesc = new javax.swing.JLabel();
        PanelDepHeader = new javax.swing.JPanel();
        labelDeposito = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescricao = new javax.swing.JTextArea();
        labelErro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoBoleto = new javax.swing.JTextArea();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelIcone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        labelOlaUsuario.setText("Olá, ");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel2.setText("N° da Conta: ");

        jLabel1.setText("N° da Agência: ");

        labelConta.setText(" ");

        labelAgencia.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAgencia)
                    .addComponent(labelConta))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelAgencia))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel3.setText("SALDO:");

        labelSaldo.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelOlaUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomeUsuario)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelIcone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSaldo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOlaUsuario)
                    .addComponent(labelNomeUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelSaldo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Área de depósito");
        setUndecorated(true);

        PanelDep.setBackground(new java.awt.Color(255, 255, 255));
        PanelDep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelQuantidade.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        labelQuantidade.setForeground(new java.awt.Color(38, 15, 38));
        labelQuantidade.setLabelFor(campoQuantidade);
        labelQuantidade.setText("Digite a quantidade:");

        campoQuantidade.setBackground(new java.awt.Color(248, 237, 248));
        campoQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        campoQuantidade.setForeground(new java.awt.Color(38, 15, 38));
        campoQuantidade.setToolTipText("Quantidade do depósito");
        campoQuantidade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));
        campoQuantidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botaoGerarBoleto.setBackground(new java.awt.Color(81, 223, 132));
        botaoGerarBoleto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoGerarBoleto.setForeground(new java.awt.Color(38, 15, 38));
        botaoGerarBoleto.setText("DEPOSITAR / GERAR BOLETO");
        botaoGerarBoleto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoGerarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarBoletoActionPerformed(evt);
            }
        });

        botaoCancelar.setBackground(new java.awt.Color(227, 38, 54));
        botaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCancelar.setText("CANCELAR");
        botaoCancelar.setToolTipText("Cancelar depósito");
        botaoCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        LabelDesc.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        LabelDesc.setForeground(new java.awt.Color(38, 15, 38));
        LabelDesc.setLabelFor(campoDescricao);
        LabelDesc.setText("Descrição: ");

        PanelDepHeader.setBackground(new java.awt.Color(0, 102, 102));
        PanelDepHeader.setForeground(new java.awt.Color(255, 255, 255));

        labelDeposito.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelDeposito.setForeground(new java.awt.Color(255, 255, 255));
        labelDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDeposito.setText("Depósito");

        javax.swing.GroupLayout PanelDepHeaderLayout = new javax.swing.GroupLayout(PanelDepHeader);
        PanelDepHeader.setLayout(PanelDepHeaderLayout);
        PanelDepHeaderLayout.setHorizontalGroup(
            PanelDepHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDepHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDepHeaderLayout.setVerticalGroup(
            PanelDepHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDepHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelDeposito)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(248, 237, 248));

        campoDescricao.setBackground(new java.awt.Color(248, 237, 248));
        campoDescricao.setColumns(20);
        campoDescricao.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        campoDescricao.setForeground(new java.awt.Color(38, 15, 38));
        campoDescricao.setRows(5);
        jScrollPane1.setViewportView(campoDescricao);

        labelErro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelErro.setForeground(new java.awt.Color(255, 0, 0));

        campoBoleto.setBackground(new java.awt.Color(248, 237, 248));
        campoBoleto.setColumns(20);
        campoBoleto.setRows(5);
        jScrollPane2.setViewportView(campoBoleto);

        javax.swing.GroupLayout PanelDepLayout = new javax.swing.GroupLayout(PanelDep);
        PanelDep.setLayout(PanelDepLayout);
        PanelDepLayout.setHorizontalGroup(
            PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDepHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDepLayout.createSequentialGroup()
                        .addGroup(PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDepLayout.createSequentialGroup()
                                .addComponent(labelQuantidade)
                                .addGap(18, 18, 18)
                                .addComponent(campoQuantidade))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDepLayout.createSequentialGroup()
                                .addComponent(LabelDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoGerarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelDepLayout.createSequentialGroup()
                                .addComponent(labelErro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(10, 10, 10))
        );
        PanelDepLayout.setVerticalGroup(
            PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDepLayout.createSequentialGroup()
                .addComponent(PanelDepHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDepLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelQuantidade)
                            .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDepLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(LabelDesc))
                            .addGroup(PanelDepLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelDepLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelErro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoGerarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoGerarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarBoletoActionPerformed
        
        campoQuantidade.setText(campoQuantidade.getText().replace(",", "."));
        
        if(campoQuantidade.getText().isEmpty() || Double.parseDouble(campoQuantidade.getText()) == 0.00){
            labelErro.setText("Campo Vazio!");
        }else{
            String boletoNumber = generateRandomBoletoNumber(47);
            campoBoleto.setText(boletoNumber);
            db.conectar();
            if(db.estaConectado()){
                
                try{
                    String descricao = campoDescricao.getText();

                    Double saldo = usuario_logado.getSaldo();
                    Double novoSaldo = saldo + Double.parseDouble(campoQuantidade.getText());
                    db.setSaldo(usuario_logado.getCpf(), novoSaldo);

                    db.inserirTransacao(usuario_logado.getCpf(), "Depósito -- " + descricao, Double.parseDouble(campoQuantidade.getText()), novoSaldo);

                    usuario_logado.setSaldo(novoSaldo);

                    String destinatario = usuario_logado.getEmail();
                    String assunto = "Depósito 3F";
                    String texto = "Olá " + usuario_logado.getNome() + ",\n\n"
                        + "O depósito em sua conta foi efetuado com sucesso.\n"
                        + "Valor do Depósito: R$" + Double.parseDouble(campoQuantidade.getText()) + "\n"
                        + "Saldo Atual: R$" + novoSaldo + "\n"
                        + "Descrição: " + descricao + "\n\n"
                        + "Agradecemos por escolher nossos serviços bancários.\n\n"
                        + "Atenciosamente,\n"
                        + "Equipe do Banco 3F";


                    email2.enviaEmailSemAnexo(destinatario, assunto, texto);
                        
                    botaoDepositar.setEnabled(true);
                }catch(Exception e){
                    labelErro.setText("Erro:" + e.getMessage());
                }
            }        
            db.desconectar();
            botaoGerarBoleto.setEnabled(false);
        }       
        
    }//GEN-LAST:event_botaoGerarBoletoActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
        botaoDepositar.setEnabled(true);
    }//GEN-LAST:event_botaoCancelarActionPerformed

    // Método para gerar boleto
    private String generateRandomBoletoNumber(int numDigits) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < numDigits; i++) {
            int digit = (int) (Math.random() * 10); // Gera um dígito de 0 a 9
            sb.append(digit);
        }
        return sb.toString();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDesc;
    private javax.swing.JPanel PanelDep;
    private javax.swing.JPanel PanelDepHeader;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoGerarBoleto;
    private javax.swing.JTextArea campoBoleto;
    private javax.swing.JTextArea campoDescricao;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAgencia;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelDeposito;
    private javax.swing.JLabel labelErro;
    private javax.swing.JLabel labelIcone;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JLabel labelOlaUsuario;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelSaldo;
    // End of variables declaration//GEN-END:variables
}
