
package bancopoo;

import dados.BdBanco;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.util.regex.Pattern;
import java.util.regex.Matcher;
import java.util.Random;
import javax.swing.ImageIcon;

import javax.swing.JButton;
import objetos.Email;


/**
 *
 * @author Fael
 */
public class painelCadastro extends javax.swing.JFrame {
    BdBanco db = new BdBanco();
    Email email2 = new Email();
    
    JButton botaoCadastro;
    
    public painelCadastro(JButton botaoCadastro) {
        ImageIcon icon = new ImageIcon("src/img/bank.png"); // Substitua pelo caminho do ícone .ico ou .png
        setIconImage(icon.getImage());
        
        initComponents();
        this.botaoCadastro = botaoCadastro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeralCadastro = new javax.swing.JPanel();
        PanelCadastroPess = new javax.swing.JPanel();
        campoCpf = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        LabelNome = new javax.swing.JLabel();
        LabelCPF = new javax.swing.JLabel();
        LabelSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JTextField();
        campoSobrenome = new javax.swing.JTextField();
        LabelSobrenome = new javax.swing.JLabel();
        LabelCelular = new javax.swing.JLabel();
        campoCelular = new javax.swing.JTextField();
        botaoFoto = new javax.swing.JButton();
        campoFoto = new javax.swing.JTextField();
        LabelSexo = new javax.swing.JLabel();
        campoSexo = new javax.swing.JComboBox<>();
        LabelNascimento = new javax.swing.JLabel();
        campoNascimento = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        PanelCadastroEnd = new javax.swing.JPanel();
        LabelEstado = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        LabelCidade = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        LabelNumero = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        LabelBairro = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        LabelRua = new javax.swing.JLabel();
        campoRua = new javax.swing.JTextField();
        LabelCEP = new javax.swing.JLabel();
        campoCep = new javax.swing.JTextField();
        botaoBuscaCep = new javax.swing.JButton();
        botaoCancelarCadastro = new javax.swing.JButton();
        botaoSalvarCadastro = new javax.swing.JButton();
        labelErro = new javax.swing.JLabel();
        PanelHeader = new javax.swing.JPanel();
        LabelCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela de cadastro");
        setBackground(new java.awt.Color(255, 204, 204));
        setUndecorated(true);
        setSize(new java.awt.Dimension(455, 587));

        PanelGeralCadastro.setBackground(new java.awt.Color(38, 15, 38));
        PanelGeralCadastro.setForeground(new java.awt.Color(255, 255, 255));
        PanelGeralCadastro.setPreferredSize(new java.awt.Dimension(500, 400));

        PanelCadastroPess.setBackground(new java.awt.Color(248, 237, 248));
        PanelCadastroPess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campoCpf.setBackground(new java.awt.Color(248, 237, 248));
        campoCpf.setColumns(8);
        campoCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCpf.setForeground(new java.awt.Color(38, 15, 38));
        campoCpf.setToolTipText("Digite seu cpf (SEM PONTUAÇÃO)");
        campoCpf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        campoNome.setBackground(new java.awt.Color(248, 237, 248));
        campoNome.setColumns(8);
        campoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNome.setForeground(new java.awt.Color(38, 15, 38));
        campoNome.setToolTipText("Digite seu primeiro nome");
        campoNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        LabelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNome.setLabelFor(campoNome);
        LabelNome.setText("*NOME:");

        LabelCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelCPF.setLabelFor(campoCpf);
        LabelCPF.setText("*CPF:");

        LabelSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSenha.setLabelFor(campoSenha);
        LabelSenha.setText("*SENHA:");

        campoSenha.setBackground(new java.awt.Color(248, 237, 248));
        campoSenha.setColumns(8);
        campoSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(38, 15, 38));
        campoSenha.setToolTipText("Digite sua senha");
        campoSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        campoSobrenome.setBackground(new java.awt.Color(248, 237, 248));
        campoSobrenome.setColumns(8);
        campoSobrenome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoSobrenome.setForeground(new java.awt.Color(38, 15, 38));
        campoSobrenome.setToolTipText("Digite seu sobrenome");
        campoSobrenome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        LabelSobrenome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSobrenome.setLabelFor(campoSobrenome);
        LabelSobrenome.setText("*SOBRENOME:");

        LabelCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelCelular.setLabelFor(campoCelular);
        LabelCelular.setText("*CELULAR:");

        campoCelular.setBackground(new java.awt.Color(248, 237, 248));
        campoCelular.setColumns(8);
        campoCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCelular.setForeground(new java.awt.Color(38, 15, 38));
        campoCelular.setToolTipText("Digite seu n° de celular");
        campoCelular.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        botaoFoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoFoto.setForeground(new java.awt.Color(38, 15, 38));
        botaoFoto.setText("FOTO");
        botaoFoto.setToolTipText("Adicionar caminho do arquivo de foto");
        botaoFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFotoActionPerformed(evt);
            }
        });

        campoFoto.setBackground(new java.awt.Color(248, 237, 248));
        campoFoto.setColumns(8);
        campoFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoFoto.setForeground(new java.awt.Color(38, 15, 38));
        campoFoto.setToolTipText("Digite o caminho do arquivo da sua foto");
        campoFoto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        LabelSexo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSexo.setLabelFor(campoSexo);
        LabelSexo.setText("*SEXO:");

        campoSexo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoSexo.setForeground(new java.awt.Color(38, 15, 38));
        campoSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não definido" }));
        campoSexo.setSelectedItem(0);
        campoSexo.setToolTipText("Selecionar sexo");
        campoSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LabelNascimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNascimento.setLabelFor(campoNascimento);
        LabelNascimento.setText("*NASCIMENTO:");

        campoNascimento.setBackground(new java.awt.Color(248, 237, 248));
        campoNascimento.setColumns(8);
        campoNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNascimento.setForeground(new java.awt.Color(38, 15, 38));
        campoNascimento.setToolTipText("xx/xx/xxxx");
        campoNascimento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        LabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelEmail.setLabelFor(campoEmail);
        LabelEmail.setText("*EMAIL:");

        campoEmail.setBackground(new java.awt.Color(248, 237, 248));
        campoEmail.setColumns(8);
        campoEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(38, 15, 38));
        campoEmail.setToolTipText("Digite seu e-mail");
        campoEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        javax.swing.GroupLayout PanelCadastroPessLayout = new javax.swing.GroupLayout(PanelCadastroPess);
        PanelCadastroPess.setLayout(PanelCadastroPessLayout);
        PanelCadastroPessLayout.setHorizontalGroup(
            PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                                .addComponent(LabelSobrenome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                                .addComponent(LabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelCPF)))
                    .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                        .addComponent(LabelEmail)
                        .addGap(18, 18, 18)
                        .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                        .addComponent(LabelSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                            .addComponent(LabelSexo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroPessLayout.createSequentialGroup()
                            .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadastroPessLayout.createSequentialGroup()
                                    .addComponent(LabelCelular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoCelular))
                                .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                                    .addComponent(LabelNascimento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(33, 33, 33)))
                    .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                        .addComponent(botaoFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        PanelCadastroPessLayout.setVerticalGroup(
            PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroPessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNascimento)
                    .addComponent(campoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSobrenome)
                    .addComponent(campoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSexo)
                    .addComponent(campoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCelular)
                    .addComponent(campoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCPF)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSenha)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFoto)
                    .addComponent(campoFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroPessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelCadastroEnd.setBackground(new java.awt.Color(248, 237, 248));
        PanelCadastroEnd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelEstado.setLabelFor(campoEstado);
        LabelEstado.setText("*ESTADO:");

        campoEstado.setBackground(new java.awt.Color(248, 237, 248));
        campoEstado.setColumns(20);
        campoEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoEstado.setForeground(new java.awt.Color(38, 15, 38));
        campoEstado.setToolTipText("Unidade Federativa");
        campoEstado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        LabelCidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelCidade.setLabelFor(campoCidade);
        LabelCidade.setText("*CIDADE:");

        campoCidade.setBackground(new java.awt.Color(248, 237, 248));
        campoCidade.setColumns(20);
        campoCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCidade.setForeground(new java.awt.Color(38, 15, 38));
        campoCidade.setToolTipText("Cidade");
        campoCidade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        LabelNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNumero.setLabelFor(campoNumero);
        LabelNumero.setText("*NÚMERO:");

        campoNumero.setBackground(new java.awt.Color(248, 237, 248));
        campoNumero.setColumns(20);
        campoNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNumero.setForeground(new java.awt.Color(38, 15, 38));
        campoNumero.setToolTipText("N° da casa");
        campoNumero.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));
        campoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroActionPerformed(evt);
            }
        });

        LabelBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelBairro.setLabelFor(campoBairro);
        LabelBairro.setText("*BAIRRO:");

        campoBairro.setBackground(new java.awt.Color(248, 237, 248));
        campoBairro.setColumns(20);
        campoBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoBairro.setForeground(new java.awt.Color(38, 15, 38));
        campoBairro.setToolTipText("Nome do bairro");
        campoBairro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        LabelRua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelRua.setLabelFor(campoRua);
        LabelRua.setText("*RUA:");

        campoRua.setBackground(new java.awt.Color(248, 237, 248));
        campoRua.setColumns(20);
        campoRua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoRua.setForeground(new java.awt.Color(38, 15, 38));
        campoRua.setToolTipText("Nome da rua");
        campoRua.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        LabelCEP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelCEP.setLabelFor(campoCep);
        LabelCEP.setText("*CEP:");

        campoCep.setBackground(new java.awt.Color(248, 237, 248));
        campoCep.setColumns(10);
        campoCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCep.setForeground(new java.awt.Color(38, 15, 38));
        campoCep.setToolTipText("Digite seu CEP (SEM PONTUAÇÃO)");
        campoCep.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));

        botaoBuscaCep.setBackground(new java.awt.Color(38, 15, 38));
        botaoBuscaCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoBuscaCep.setForeground(new java.awt.Color(255, 255, 255));
        botaoBuscaCep.setText("BUSCA");
        botaoBuscaCep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoBuscaCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscaCepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastroEndLayout = new javax.swing.GroupLayout(PanelCadastroEnd);
        PanelCadastroEnd.setLayout(PanelCadastroEndLayout);
        PanelCadastroEndLayout.setHorizontalGroup(
            PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroEndLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelCEP)
                    .addComponent(LabelRua)
                    .addComponent(LabelBairro)
                    .addGroup(PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelCidade)
                        .addComponent(LabelEstado))
                    .addComponent(LabelNumero))
                .addGap(18, 18, 18)
                .addGroup(PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCadastroEndLayout.createSequentialGroup()
                        .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoBuscaCep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCadastroEndLayout.setVerticalGroup(
            PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroEndLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCEP)
                    .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscaCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRua)
                    .addComponent(campoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCidade)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEstado))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        campoCep.getAccessibleContext().setAccessibleName("aaa");

        botaoCancelarCadastro.setBackground(new java.awt.Color(227, 38, 54));
        botaoCancelarCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoCancelarCadastro.setForeground(new java.awt.Color(255, 255, 255));
        botaoCancelarCadastro.setText("CANCELAR");
        botaoCancelarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarCadastroActionPerformed(evt);
            }
        });

        botaoSalvarCadastro.setBackground(new java.awt.Color(81, 223, 132));
        botaoSalvarCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoSalvarCadastro.setForeground(new java.awt.Color(38, 15, 38));
        botaoSalvarCadastro.setText("SALVAR");
        botaoSalvarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarCadastroActionPerformed(evt);
            }
        });

        labelErro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelErro.setForeground(new java.awt.Color(255, 51, 51));
        labelErro.setText(" ");

        PanelHeader.setBackground(new java.awt.Color(81, 223, 132));

        LabelCadastro.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        LabelCadastro.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastro.setText("Cadastro");

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(LabelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(LabelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelGeralCadastroLayout = new javax.swing.GroupLayout(PanelGeralCadastro);
        PanelGeralCadastro.setLayout(PanelGeralCadastroLayout);
        PanelGeralCadastroLayout.setHorizontalGroup(
            PanelGeralCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGeralCadastroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelGeralCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelGeralCadastroLayout.createSequentialGroup()
                        .addComponent(labelErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoSalvarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(botaoCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelCadastroEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCadastroPess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        PanelGeralCadastroLayout.setVerticalGroup(
            PanelGeralCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeralCadastroLayout.createSequentialGroup()
                .addComponent(PanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PanelCadastroPess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCadastroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelGeralCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGeralCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelGeralCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoSalvarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(botaoCancelarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(PanelGeralCadastroLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeralCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGeralCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroActionPerformed

    private void botaoSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarCadastroActionPerformed
        try{
            
            String cpf = campoCpf.getText();
            String nome = campoNome.getText();
            String sobrenome = campoSobrenome.getText();
            String nascimento = campoNascimento.getText();
            String sexo = (String) campoSexo.getSelectedItem();
            String senha = campoSenha.getText();
            String celular = campoCelular.getText();
            String email = campoEmail.getText();
            
            String cep = campoCep.getText();
            String rua = campoRua.getText();
            String bairro = campoBairro.getText();
            int numero = Integer.parseInt(campoNumero.getText());
            String cidade = campoCidade.getText();
            String estado = campoEstado.getText();

            String foto = campoFoto.getText();
            db.conectar();
            if(db.verificaCpfRepetido(cpf)){
                labelErro.setText("O CPF já está cadastrado!");
                //JOptionPane.showMessageDialog(null, "O CPF já está cadastrado, caso não lembre a senha vá em RECUPERAR SENHA","CPF JÁ CADASTRADO", JOptionPane.ERROR_MESSAGE);
            }else{
                if (cpf == null || cpf.isEmpty()  || cpf.length() != 11||
                    nome == null || nome.isEmpty() ||
                    sobrenome == null || sobrenome.isEmpty() ||
                    nascimento == null || nascimento.isEmpty()  || validaDataNascimento(nascimento) == false ||
                    sexo == null ||
                    senha == null || senha.isEmpty() ||
                    celular == null || celular.isEmpty() ||
                    cep == null || cep.isEmpty() ||
                    rua == null || rua.isEmpty() ||
                    bairro == null || bairro.isEmpty() ||
                    cidade == null || cidade.isEmpty() ||
                    estado == null || estado.isEmpty()||
                    email == null || email.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Alternativas que podem estar dando erradas:\nPreencha todos os campos obrigatórios antes de salvar. \nSe atentar no formato de preenchimento dos campos DATA e CEP.\nCuidado com o CPF","Campos obrigatórios vazios", JOptionPane.ERROR_MESSAGE);
                }else{
                    int opcao = JOptionPane.showConfirmDialog(this,"Tem certeza que deseja criar uma nova conta?","Confirmação",JOptionPane.YES_NO_OPTION);
                    if (opcao == JOptionPane.YES_OPTION) {
                        
                        if(db.estaConectado()){
                            Random random = new Random();
                            String recuperacao;
                            do{
                                recuperacao = String.valueOf(random.nextInt(900000000) + 100000000);
                            }while(db.verificaRecuperacaoRepetido(recuperacao));


                            String conta;    
                            do{
                                conta = String.valueOf(random.nextInt(900000000) + 100000000);
                            }while(db.verificaContaRepetido(conta));



                            db.inserirUsuarioDB(cpf, senha, nome, sobrenome, email, nascimento, sexo, celular, rua, bairro, numero, cidade, estado, cep, foto, recuperacao, conta, "3307");
                            
                            
                            String destinatario = email;
                            String assunto = "Conta 3F criada!";
                            String texto = "Olá " + nome + ",\n\n"
                                    + "Parabéns! Sua nova conta bancária foi criada com sucesso.\n"
                                    + "Número da Conta: " + conta + "\n"
                                    + "NÃO PERCA SUA CHAVE DE RECUPERAÇÃO: "+ recuperacao +"\n\n" 
                                    + "Agradecemos por escolher nossos serviços bancários.\n\n"
                                    + "Atenciosamente,\n"
                                    + "Equipe do Banco 3F";


                            email2.enviaEmailSemAnexo(destinatario, assunto, texto);
                            
                                
                            
                            this.dispose();
                            JOptionPane.showMessageDialog(null, "Dados salvos no sistema\nGuarde sua chave de recuperação de senha: \n" + recuperacao , "MUITO IMPORTANTE!", JOptionPane.WARNING_MESSAGE);

                        }else{
                            JOptionPane.showMessageDialog(null, "Banco de dados não está conectado!", "Database inválida", JOptionPane.ERROR_MESSAGE);
                        }
                        db.desconectar();

                    }else{
                        JOptionPane.showMessageDialog(this, "Operação cancelada pelo usuário.", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
            
            botaoCadastro.setEnabled(true);
        }catch(Exception e){
            labelErro.setText("Você precisa preencher os campos!\n" + e.getMessage());
            //JOptionPane.showMessageDialog(null, "Você precisa preencher os campos!\n" + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_botaoSalvarCadastroActionPerformed

    public static boolean validaDataNascimento(String nascimento) {
        // Expressão regular para verificar o formato 'dd/mm/aaaa' com barras
        String verificacao = "^(0[1-9]|[1-2][0-9]|3[0-1])/(0[1-9]|1[0-2])/\\d{4}$";
        Pattern pattern = Pattern.compile(verificacao);
        Matcher matcher = pattern.matcher(nascimento);
        return matcher.matches();
    }
    
    
    private void botaoCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarCadastroActionPerformed
        this.dispose();
        botaoCadastro.setEnabled(true);
        
    }//GEN-LAST:event_botaoCancelarCadastroActionPerformed
    
    
    
    private String getValueFromJson(String jsonString, String key) {
            int keyIndex = jsonString.indexOf("\"" + key + "\":");
            int valueIndex = jsonString.indexOf("\"", keyIndex + key.length() + 3);
            int endIndex = jsonString.indexOf("\"", valueIndex + 1);

            if (valueIndex > keyIndex && valueIndex < endIndex) {
                return jsonString.substring(valueIndex + 1, endIndex);
            }

            return "";
    }
    
    private void botaoBuscaCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscaCepActionPerformed
        String cep = campoCep.getText();
        if (cep.length() != 8 || !cep.matches("[0-9]+")) {
            //JOptionPane.showMessageDialog(null, "CEP inválido. Certifique-se de digitar um CEP válido com 8 dígitos numéricos.", "CEP Inválido", JOptionPane.ERROR_MESSAGE);
            labelErro.setText("CEP inválido. Certifique-se de digitar um CEP válido com 8 dígitos numéricos.");
            return;
        }
        try {
                String urlStr = "https://viacep.com.br/ws/" + cep + "/json/";
                URL url = new URL(urlStr);
                HttpURLConnection conn = (HttpURLConnection) url.openConnection();
                conn.setRequestMethod("GET");

                if (conn.getResponseCode() == 200) {
                    BufferedReader br = new BufferedReader(new InputStreamReader(conn.getInputStream()));
                    StringBuilder jsonText = new StringBuilder();
                    String line;

                    while ((line = br.readLine()) != null) {
                        jsonText.append(line);
                    }

                    br.close();
                    
                    // Since we're using only native libraries, we parse the JSON manually
                    String jsonString = jsonText.toString();
                    String logradouro = getValueFromJson(jsonString, "logradouro");
                    String bairro = getValueFromJson(jsonString, "bairro");
                    String localidade = getValueFromJson(jsonString, "localidade");
                    String uf = getValueFromJson(jsonString, "uf");
                    
                    System.out.println(logradouro);
                    
                    campoRua.setText(logradouro);
                    campoBairro.setText(bairro);
                    campoCidade.setText(localidade);
                    campoEstado.setText(uf);
                    
                } else {
                    labelErro.setText("CEP não encontrado. Verifique se o CEP está correto.");
                    //JOptionPane.showMessageDialog(null, "CEP não encontrado. Verifique se o CEP está correto.", "CEP não Encontrado", JOptionPane.WARNING_MESSAGE);
                }

                conn.disconnect();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao realizar a busca por CEP. Verifique sua conexão de internet.", "Erro de Conexão", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_botaoBuscaCepActionPerformed

    private void botaoFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagens", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            campoFoto.setText(selectedFile.getAbsolutePath());
    }
        
    
        
        
    }//GEN-LAST:event_botaoFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
        //    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        //        if ("Nimbus".equals(info.getName())) {
        //            javax.swing.UIManager.setLookAndFeel(info.getClassName());
        //            break;
        //        }
        //    }
        //} catch (ClassNotFoundException ex) {
        //    java.util.logging.Logger.getLogger(painelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (InstantiationException ex) {
        //    java.util.logging.Logger.getLogger(painelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (IllegalAccessException ex) {
        //    java.util.logging.Logger.getLogger(painelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //    java.util.logging.Logger.getLogger(painelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //}
        //</editor-fold>

        /* Create and display the form */
    //    java.awt.EventQueue.invokeLater(new Runnable() {
    //        public void run() {
    //            new painelCadastro().setVisible(true);
    //        }
    //    });
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelCEP;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelCadastro;
    private javax.swing.JLabel LabelCelular;
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JLabel LabelNascimento;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelRua;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LabelSexo;
    private javax.swing.JLabel LabelSobrenome;
    private javax.swing.JPanel PanelCadastroEnd;
    private javax.swing.JPanel PanelCadastroPess;
    private javax.swing.JPanel PanelGeralCadastro;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JButton botaoBuscaCep;
    private javax.swing.JButton botaoCancelarCadastro;
    private javax.swing.JButton botaoFoto;
    private javax.swing.JButton botaoSalvarCadastro;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCelular;
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextField campoFoto;
    private javax.swing.JTextField campoNascimento;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRua;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JComboBox<String> campoSexo;
    private javax.swing.JTextField campoSobrenome;
    private javax.swing.JLabel labelErro;
    // End of variables declaration//GEN-END:variables
}
