/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bancopoo;

import dados.BdBanco;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;





public class painelLogin extends javax.swing.JFrame {
    private painelPrincipal principal;
    
    BdBanco db = new BdBanco();
    
  
    
    
    public painelLogin() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/img/bank.png"); // Substitua pelo caminho do ícone .ico ou .png
        setIconImage(icon.getImage());
    }
    
    public painelLogin(painelPrincipal principal) {
        initComponents();
        this.principal = principal;
        ImageIcon icon = new ImageIcon("src/img/bank.png"); // Substitua pelo caminho do ícone .ico ou .png
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLoginGeral = new javax.swing.JPanel();
        PanelLogo = new javax.swing.JPanel();
        labelImagemBanco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanelAcoes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        botaoEntrar = new javax.swing.JButton();
        campoSenha = new javax.swing.JPasswordField();
        botaoEsqueceuSenha = new javax.swing.JButton();
        botaoCadastro = new javax.swing.JButton();
        LabelNovaConta = new javax.swing.JLabel();
        LabelRecSenha = new javax.swing.JLabel();
        labelErro = new javax.swing.JLabel();
        labelSucesso = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3F");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        PanelLoginGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PanelLogo.setBackground(new java.awt.Color(38, 15, 38));
        PanelLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        labelImagemBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO 3F GRANDE.png"))); // NOI18N
        labelImagemBanco.setToolTipText("3F Intenet Banking");

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BANCO 3F");

        jLabel5.setBackground(new java.awt.Color(38, 15, 38));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("© Todos direitos Reservados - 3F");

        javax.swing.GroupLayout PanelLogoLayout = new javax.swing.GroupLayout(PanelLogo);
        PanelLogo.setLayout(PanelLogoLayout);
        PanelLogoLayout.setHorizontalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImagemBanco))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        PanelLogoLayout.setVerticalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(labelImagemBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelAcoes.setBackground(new java.awt.Color(255, 255, 255));
        PanelAcoes.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(38, 15, 38));
        labelLogin.setLabelFor(campoCpf);
        labelLogin.setText("Cpf");

        campoCpf.setColumns(12);
        campoCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoCpf.setForeground(new java.awt.Color(38, 15, 38));
        campoCpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoCpf.setToolTipText("Digite seu CPF");
        campoCpf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));
        campoCpf.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                campoCpfCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                campoCpfInputMethodTextChanged(evt);
            }
        });
        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });
        campoCpf.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                campoCpfPropertyChange(evt);
            }
        });

        labelSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(38, 15, 38));
        labelSenha.setLabelFor(campoSenha);
        labelSenha.setText("Senha");

        botaoEntrar.setBackground(new java.awt.Color(38, 15, 38));
        botaoEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoEntrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrar.setMnemonic(10);
        botaoEntrar.setText("ENTRAR");
        botaoEntrar.setToolTipText("Entre no sistema");
        botaoEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });

        campoSenha.setColumns(12);
        campoSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(38, 15, 38));
        campoSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoSenha.setToolTipText("Digite sua senha");
        campoSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 15, 38)));
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });

        botaoEsqueceuSenha.setBackground(new java.awt.Color(38, 15, 38));
        botaoEsqueceuSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoEsqueceuSenha.setForeground(new java.awt.Color(255, 255, 255));
        botaoEsqueceuSenha.setText("ESQUECI A SENHA");
        botaoEsqueceuSenha.setToolTipText("Recuperação de senha");
        botaoEsqueceuSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEsqueceuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEsqueceuSenhaActionPerformed(evt);
            }
        });

        botaoCadastro.setBackground(new java.awt.Color(81, 223, 132));
        botaoCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCadastro.setForeground(new java.awt.Color(38, 15, 38));
        botaoCadastro.setText("CRIAR CONTA");
        botaoCadastro.setToolTipText("Criação de conta");
        botaoCadastro.setBorder(null);
        botaoCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastro.setMaximumSize(new java.awt.Dimension(131, 23));
        botaoCadastro.setMinimumSize(new java.awt.Dimension(131, 23));
        botaoCadastro.setPreferredSize(new java.awt.Dimension(131, 23));
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        LabelNovaConta.setForeground(new java.awt.Color(38, 15, 38));
        LabelNovaConta.setLabelFor(botaoCadastro);
        LabelNovaConta.setText("Ainda não tem conta?");

        LabelRecSenha.setForeground(new java.awt.Color(38, 15, 38));
        LabelRecSenha.setLabelFor(botaoEsqueceuSenha);
        LabelRecSenha.setText("Não se lembra da senha?");

        labelErro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelErro.setForeground(new java.awt.Color(255, 51, 51));
        labelErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelErro.setText(" ");

        labelSucesso.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelSucesso.setForeground(new java.awt.Color(0, 204, 0));
        labelSucesso.setText(" ");
        labelSucesso.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelRecSenha)
                    .addComponent(LabelNovaConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoEsqueceuSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelSenha)
                        .addGap(18, 18, 18)
                        .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelLogin)
                        .addGap(18, 18, 18)
                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSucesso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelErro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLogin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSucesso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRecSenha)
                    .addComponent(botaoEsqueceuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNovaConta))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        botaoSair.setBackground(new java.awt.Color(227, 38, 54));
        botaoSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("SAIR");
        botaoSair.setToolTipText("Feche o sistema");
        botaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAcoesLayout = new javax.swing.GroupLayout(PanelAcoes);
        PanelAcoes.setLayout(PanelAcoesLayout);
        PanelAcoesLayout.setHorizontalGroup(
            PanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAcoesLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelAcoesLayout.setVerticalGroup(
            PanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAcoesLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelLoginGeralLayout = new javax.swing.GroupLayout(PanelLoginGeral);
        PanelLoginGeral.setLayout(PanelLoginGeralLayout);
        PanelLoginGeralLayout.setHorizontalGroup(
            PanelLoginGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginGeralLayout.createSequentialGroup()
                .addComponent(PanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        PanelLoginGeralLayout.setVerticalGroup(
            PanelLoginGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLoginGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLoginGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        botaoEntrar.doClick();
    }//GEN-LAST:event_campoCpfActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        botaoEntrar.doClick();
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        
        String cpf = campoCpf.getText();
        String senha = campoSenha.getText();
        try{
            if (!cpf.isEmpty() && !senha.isEmpty()){
                db.conectar();
                if(db.verificaUsuario(cpf, senha) ){
                   mostrarTelaPrincipal(cpf);

                }else{
                    labelErro.setText("Não foi possível verificar suas informações!");
                    //JOptionPane.showMessageDialog(null, "Não foi possível verificar suas informações!", "Erro", JOptionPane.ERROR_MESSAGE);
                    campoSenha.setText("");
                }
                db.desconectar();
            }else{
                labelErro.setText("Os campos CPF e SENHA não podem estar vazios!");
                //JOptionPane.showMessageDialog(null, "Os campos CPF e SENHA não podem estar vazios!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            labelErro.setText("Ocorreu um erro inesperado: " + e.getMessage());
            //JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        mostrarTelaCadastro();     
    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void botaoEsqueceuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEsqueceuSenhaActionPerformed
        String cpf = JOptionPane.showInputDialog(null, "Digite seu CPF:", "Recuperação de senha", JOptionPane.PLAIN_MESSAGE);
        String recuperacao = JOptionPane.showInputDialog(null, "Digite seu número de recuperação:", "Recuperação de senha", JOptionPane.PLAIN_MESSAGE);        
        
        db.conectar();
        if(db.estaConectado()){            
            if(db.verificaEsqueceuSenha(cpf, recuperacao)){
                String senhaNova = JOptionPane.showInputDialog(null, "Digite sua senha nova: ", "Recuperação de senha", JOptionPane.PLAIN_MESSAGE);
                db.editarSenhaDB(cpf, senhaNova);

                labelSucesso.setText("Senha alterada com sucesso!");
                //JOptionPane.showMessageDialog(null, "Senha alterada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }else{
                labelErro.setText("Não foi possível relacionar o código de recuperação com o CPF fornecido.");
                //JOptionPane.showMessageDialog(null, "Não foi possível relacionar o código de recuperação com o CPF fornecido.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "O Banco de dados não está conectado: ", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        db.desconectar();
        
    }//GEN-LAST:event_botaoEsqueceuSenhaActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void campoCpfInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_campoCpfInputMethodTextChanged
        
    }//GEN-LAST:event_campoCpfInputMethodTextChanged

    private void campoCpfPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_campoCpfPropertyChange
        
    }//GEN-LAST:event_campoCpfPropertyChange

    private void campoCpfCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_campoCpfCaretPositionChanged
        
    }//GEN-LAST:event_campoCpfCaretPositionChanged
    
    
    private void mostrarTelaCadastro(){
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                botaoCadastro.setEnabled(false);
                painelCadastro cadastro = new painelCadastro(botaoCadastro);
                cadastro.setLocationRelativeTo(null);
                cadastro.pack();
                cadastro.setVisible(true);
                
            }
        });
    }
    
    private void mostrarTelaPrincipal(String cpf) {
        // Oculta a tela de login atual
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                painelPrincipal principal = new painelPrincipal(cpf);
                
                //principal.setExtendedState(JFrame.MAXIMIZED_BOTH);
                
                principal.setLocationRelativeTo(null);// Torna a tela principal visível
                principal.setVisible(true);
                
            }
        });
        
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(painelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(painelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(painelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(painelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                painelLogin login = new painelLogin();
                
                login.setVisible(true);
                login.setLocationRelativeTo(null);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNovaConta;
    private javax.swing.JLabel LabelRecSenha;
    private javax.swing.JPanel PanelAcoes;
    private javax.swing.JPanel PanelLoginGeral;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JButton botaoEsqueceuSenha;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelErro;
    private javax.swing.JLabel labelImagemBanco;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSucesso;
    // End of variables declaration//GEN-END:variables
}
